#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

SCRIPT="/etc/jadwalsholat/jadwalsholatbot.py"
NAME=jadwalsholatbot

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 "$SCRIPT"
    procd_set_param respawn 3600 5 5   # Lebih aman daripada default kosong
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
